//	Random comment
.create table ['my-table'] (a: real, b: int, c: string)

.create table ['my-table2'] (Id:string)

.alter table ['my-table'] policy ingestionbatching
```
{
  "MaximumBatchingTimeSpan": "00:05:00",
  "MaximumNumberOfItems": 1000, 
  "MaximumRawDataSizeMB": 5
}
```

.alter table ['my-table2'] policy ingestionbatching
```
{
  "MaximumBatchingTimeSpan": "00:05:00",
  "MaximumNumberOfItems": 1000, 
  "MaximumRawDataSizeMB": 5
}
```