.create table GithubEvent (Id: int, Type: string, Actor: dynamic, Repo: dynamic, Payload: dynamic, CreatedAt: datetime) with (folder="git", docstring="events")

.alter-merge table GithubEvent column-docstrings (Actor:"Person doing action", Payload:"JSON describing the event")

.create table OccupancyDetection (Timestamp: datetime, Temperature: real, Humidity: real, Light: real, CO2: real, HumidityRatio: real, Occupancy: bool, Test: bool) 
